const ActionTypes = {
  //AUTH login
  FETCH_AUTH_LOGIN: "FETCH_AUTH_LOGIN",
  SET_AUTH_LOGIN: "SET_AUTH_LOGIN",
  //AUTH login
  FETCH_AUTH_REGISTER: "FETCH_AUTH_REGISTER",
  SET_AUTH_REGISTER: "SET_AUTH_REGISTER",

  //set origin coordinates
  SET_ORIGIN_COORDINATES: "SET_ORIGIN_COORDINATES",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",

  //Forgett Password
  FETCH_FORGETT_PASSWORD_EMAIL_OTP: "FETCH_FORGETT_PASSWORD_EMAIL_OTP",
  SET_FORGETT_PASSWORD_EMAIL_OTP: "SET_FORGETT_PASSWORD_EMAIL_OTP",

  FETCH_VERIFY_RESET_PASSWORD_OTP: "FETCH_VERIFY_RESET_PASSWORD_OTP",
  SET_VERIFY_RESET_PASSWORD_OTP: "SET_VERIFY_RESET_PASSWORD_OTP",

  FETCH_RESET_PASSWORD: "FETCH_RESET_PASSWORD",
  SET_RESET_PASSWORD: "SET_RESET_PASSWORD",

  FETCH_SCHOOL_DIS_TIME: "FETCH_SCHOOL_DIS_TIME",
  SET_SCHOOL_DIS_TIME: "SET_SCHOOL_DIS_TIME",

  //get schools by id
  FETCH_SCHOOL_BY_ID: "FETCH_SCHOOL_BY_ID",
  SET_SCHOOL_BY_ID: "SET_SCHOOL_BY_ID",
  //get schools by id
  FETCH_ALL_SCHOOLS: "FETCH_ALL_SCHOOLS",
  SET_ALL_SCHOOLS: "SET_ALL_SCHOOLS",

  //fav unfav
  FETCH_SCHOOL_FAVORITE: "FETCH_SCHOOL_FAVORITE",
  SET_SCHOOL_FAVORITE: "SET_SCHOOL_FAVORITE",
  //fav unfav
  FETCH_SAVED_SCHOOLS: "FETCH_SAVED_SCHOOLS",
  SET_SAVED_SCHOOLS: "SET_SAVED_SCHOOLS",
};

export default ActionTypes;
