const ActionTypes = {
  //AUTH login
  FETCH_AUTH_LOGIN: "FETCH_AUTH_LOGIN",
  SET_AUTH_LOGIN: "SET_AUTH_LOGIN",
  //AUTH login
  FETCH_AUTH_REGISTER: "FETCH_AUTH_REGISTER",
  SET_AUTH_REGISTER: "SET_AUTH_REGISTER",

  //set origin coordinates
  SET_ORIGIN_COORDINATES: "SET_ORIGIN_COORDINATES",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",

  //Forgett Password
  FETCH_FORGETT_PASSWORD_EMAIL_OTP: "FETCH_FORGETT_PASSWORD_EMAIL_OTP",
  SET_FORGETT_PASSWORD_EMAIL_OTP: "SET_FORGETT_PASSWORD_EMAIL_OTP",

  FETCH_VERIFY_RESET_PASSWORD_OTP: "FETCH_VERIFY_RESET_PASSWORD_OTP",
  SET_VERIFY_RESET_PASSWORD_OTP: "SET_VERIFY_RESET_PASSWORD_OTP",

  FETCH_RESET_PASSWORD: "FETCH_RESET_PASSWORD",
  SET_RESET_PASSWORD: "SET_RESET_PASSWORD",

  FETCH_POST_DIS_TIME: "FETCH_POST_DIS_TIME",
  SET_POST_DIS_TIME: "SET_POST_DIS_TIME",

  //get posts by id
  FETCH_POST_BY_ID: "FETCH_POST_BY_ID",
  SET_POST_BY_ID: "SET_POST_BY_ID",
  //get posts by id
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  SET_ALL_POSTS: "SET_ALL_POSTS",

  //fav unfav
  FETCH_POST_FAVORITE: "FETCH_POST_FAVORITE",
  SET_POST_FAVORITE: "SET_POST_FAVORITE",
  //fav unfav
  FETCH_SAVED_POSTS: "FETCH_SAVED_POSTS",
  SET_SAVED_POSTS: "SET_SAVED_POSTS",
};

export default ActionTypes;
