const ProfleTypes = {
  FETCH_UPDATED_PROFILE: "FETCH_UPDATED_PROFILE",
  SET_UPDATED_PROFILE: "SET_UPDATED_PROFILE",

  ////PASSWORD
  FETCH_UPDATED_PASSWORD: "FETCH_UPDATED_PASSWORD",
  SET_UPDATED_PASSWORD: "SET_UPDATED_PASSWORD",

  //user profile data
  FETCH_USER_PROFILE_DATA: "FETCH_USER_PROFILE_DATA",
  SET_USER_PROFILE_DATA: "SET_USER_PROFILE_DATA",

  FETCH_UPDATED_PROFILE_PHOTO: "FETCH_UPDATED_PROFILE_PHOTO",
  SET_UPDATED_PROFILE_PHOTO: "SET_UPDATED_PROFILE_PHOTO",
};

export default ProfleTypes;
