export const loginTypes = {
  FETCH_AUTH_LOGIN: "FETCH_AUTH_LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SET_USER_DATA: "SET_USER_DATA",
  REMOVE_USER_DATA: "REMOVE_USER_DATA",

  // =========register========
  FETCH_REGISTER_USER: "FETCH_REGISTER_USER",
  SET_REGISTER_USER: "SET_REGISTER_USER",
};
