export const MainScreenSchoolTypes = {
  //GET HOMEPAGE SCHOOLS
  FETCH_HOMEPAGE_SCHOOLS: "FETCH_HOMEPAGE_SCHOOLS",
  SET_HOMEPAGE_SCHOOLS: "SET_HOMEPAGE_SCHOOLS",

  //GET HOMEPAGE SCHOOLS
  FETCH_ROUTE_QUERY_SCHOOLS: "FETCH_ROUTE_QUERY_SCHOOLS",
  SET_ROUTE_QUERY_SCHOOLS: "SET_ROUTE_QUERY_SCHOOLS",

  //GET NEARBY SCHOOLS
  FETCH_NEARBY_SCHOOLS: "FETCH_NEARBY_SCHOOLS",
  SET_NEARBY_SCHOOLS: "SET_NEARBY_SCHOOLS",

  //GET FEATURED SCHOOLS
  FETCH_FEATURED_SCHOOLS: "FETCH_FEATURED_SCHOOLS",
  SET_FEATURED_SCHOOLS: "SET_FEATURED_SCHOOLS",

  //GET TOPRATED SCHOOLS
  FETCH_TOPRATED_SCHOOLS: "FETCH_TOPRATED_SCHOOLS",
  SET_TOPRATED_SCHOOLS: "SET_TOPRATED_SCHOOLS",

  // FETCH SCHOOLS BY ID
  FETCH_SCHOOL_BY_ID: "FETCH_SCHOOL_BY_ID",
  SET_SCHOOL_BY_ID: "SET_SCHOOL_BY_ID",
};
