export const MainScreenPostTypes = {
  //GET HOMEPAGE POST
  FETCH_HOMEPAGE_POST: "FETCH_HOMEPAGE_POST",
  SET_HOMEPAGE_POST: "SET_HOMEPAGE_POST",

  //GET HOMEPAGE POST
  FETCH_ROUTE_QUERY_POST: "FETCH_ROUTE_QUERY_POST",
  SET_ROUTE_QUERY_POST: "SET_ROUTE_QUERY_POST",

  //GET NEARBY POST
  FETCH_NEARBY_POST: "FETCH_NEARBY_POST",
  SET_NEARBY_POST: "SET_NEARBY_POST",

  //GET FEATURED POST
  FETCH_FEATURED_POST: "FETCH_FEATURED_POST",
  SET_FEATURED_POST: "SET_FEATURED_POST",

  //GET TOPRATED POST
  FETCH_TOPRATED_POST: "FETCH_TOPRATED_POST",
  SET_TOPRATED_POST: "SET_TOPRATED_POST",

  // FETCH POST BY ID
  FETCH_POST_BY_ID: "FETCH_POST_BY_ID",
  SET_POST_BY_ID: "SET_POST_BY_ID",
};
