export const FindSchoolTypes = {
  //GET HOMEPAGE SCHOOLS
  FETCH_FIND_SCHOOLS: "FETCH_FIND_SCHOOLS",
  SET_FIND_SCHOOLS: "SET_FIND_SCHOOLS",

  ///saved school
  FETCH_SAVED_SCHOOLS: "FETCH_SAVED_SCHOOLS",
  SET_SAVED_SCHOOLS: "SET_SAVED_SCHOOLS",

  ///add to favourite school
  FETCH_ADDSAVED_SCHOOLS: "FETCH_ADDSAVED_SCHOOLS",
  SET_ADDSAVED_SCHOOLS: "SET_ADDSAVED_SCHOOLS",

  ///Open review modal
  OPEN_REVIEW_MODAL: "OPEN_REVIEW_MODAL",
  CLOSE_REVIEW_MODAL: "CLOSE_REVIEW_MODAL",

  ///add to review
  FETCH_ADD_REVIEW: "FETCH_ADD_REVIEW",
  SET_ADD_REVIEW: "SET_ADD_REVIEW",

  ///fetch reviews
  FETCH_REVIEW: "FETCH_REVIEW",
  SET_REVIEW: "SET_REVIEW",

  // fetch school by id
  FETCH_SCHOOL_BY_ID: "FETCH_SCHOOL_BY_ID",
  SET_SCHOOL_BY_ID: "SET_SCHOOL_BY_ID",

  // Send enquiry to school
  FETCH_SEND_SCHOOL_ENQUIRY: "FETCH_SEND_SCHOOL_ENQUIRY",
  SET_SEND_SCHOOL_ENQUIRY: "SET_SEND_SCHOOL_ENQUIRY",
};
