export const FindPostTypes = {
  //GET HOMEPAGE POST
  FETCH_FIND_POSTS: "FETCH_FIND_POSTS",
  SET_FIND_POSTS: "SET_FIND_POSTS",

  ///saved post
  FETCH_SAVED_POSTS: "FETCH_SAVED_POSTS",
  SET_SAVED_POSTS: "SET_SAVED_POSTS",

  ///add to favourite post
  FETCH_ADDSAVED_POSTS: "FETCH_ADDSAVED_POSTS",
  SET_ADDSAVED_POSTS: "SET_ADDSAVED_POSTS",

  ///Open review modal
  OPEN_REVIEW_MODAL: "OPEN_REVIEW_MODAL",
  CLOSE_REVIEW_MODAL: "CLOSE_REVIEW_MODAL",

  ///add to review
  FETCH_ADD_REVIEW: "FETCH_ADD_REVIEW",
  SET_ADD_REVIEW: "SET_ADD_REVIEW",

  ///fetch reviews
  FETCH_REVIEW: "FETCH_REVIEW",
  SET_REVIEW: "SET_REVIEW",

  // fetch post by id
  FETCH_POSTS_BY_ID: "FETCH_POSTS_BY_ID",
  SET_POSTS_BY_ID: "SET_POSTS_BY_ID",

  // Send enquiry to post
  FETCH_SEND_POSTS_ENQUIRY: "FETCH_SEND_POSTS_ENQUIRY",
  SET_SEND_POSTS_ENQUIRY: "SET_SEND_POSTS_ENQUIRY",
};
